config/routes.rb
Rails.application.routes.draw do
  get 'lapin/show'
  get '/goodbye', to: 'pages#goodbye'
  devise_for :users
  root to: 'pages#home'
  # 'get' to: 'meetings#lapin'
  resources :meetings, only: :show do
    resources :lapins, only: [:create]
    resources :feedbacks

    member do
      get :pre_show
    end
  end
  resources :lapins, only: [:show]

  resources :likes, only: :create
  resources :unlikes, only: :create
  resources :users, only: [:create, :index, :show, :edit, :update, :new]
  resources :availabilities, only: [ :index, :update ]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resource :profile, only: [:show, :update]
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user1, class_name: 'User'
  belongs_to :user2, class_name: 'User'
  belongs_to :place
  has_many :feedbacks

  validates :user1_id, :user2_id, :place_id, :start_hour, :start_time, presence: true
  STATUS = ["cancelled", "occured"]


  def time_for_feedback?
    # (time du debut du meeting + 30min ) > Time.zone.now
    # DateTime.new(start_time,start_hour) > Time.zone.now

  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  TRANSLATIONS = {
  janvier: "January",
  février: "February",
  mars: "March",
  avril: "April",
  mai: "May",
  juin: "June",
  juillet: "July" ,
  août: "August",
  septembre: "September",
  octobre: "October",
  novembre: "November",
  décembre: "December"
}
  def show


    @meeting = Meeting.find(params[:id])

    redirect_to "feedback path" if @meeting.time_for_feedback?


    @place = @meeting.place
    @liked_user = if @meeting.user2.id == current_user.id
                    @meeting.user1
                  else
                    @meeting.user2
                  end
    @like = Like.find_by(user: current_user, liked_user: @liked_user)

    @day = @meeting.start_time.day
    month_en = @meeting.start_time.strftime('%B')
    @month = TRANSLATIONS.key(month_en)
    @hour =  @meeting.start_hour.strftime('%S')

    authorize @meeting
  end

  def pre_show
    @meeting = Meeting.find(params[:id])
    authorize @meeting
  end

end

app/views/meetings/pre_show.html.erb
<div class="page" style="background-image:linear-gradient(180deg, rgba(74, 222, 222, 0.05) 71.48%, rgba(46, 188, 231, 0.7) 93.1%, #1CA7EC 100%), url('http://res.cloudinary.com/dlh4cl5ih/image/upload/<%= @meeting.user2.photos[0].key%>');">
     <div class="match-love" style="background-image: url(<%= image_path('logo_comptoir_match.svg')%>)">
     </div>

    <h2 class="preshow-card-name love-title" ><div class="name-date"><%=@meeting.user2.name %></div><div class="sous-name-date">souhaite aussi te rencontrer !</div></h2>

     <%= link_to 'Voir mon date', meeting_path(@meeting), class: "btn btn-white-date" %>
     <%= link_to "Annuler le date",  meeting_lapins_path(@meeting), method: :post, class: "btn-date-annulation"%>
</div>

app/views/meetings/show.html.erb
  <div class="meeting-topbar">
    <div class="center-text-meeting">
      <%= image_tag "LogoComptoir.png", alt: "alttext", style: "height:7vh"%>
      <h1 class="shadowing">Ton date</h1>
    </div>
    <div class="row-meeting">
      <div class="col-avatar">
        <%= link_to user_path(@liked_user) do  %>
          <%= cl_image_tag "#{@liked_user.photos[0].key}", alt: "match photo", class: "avatar-date" %>
        <% end %>
      </div>
      <div class="col-text" >
        <p class= "with shadowing">avec</p>
        <%= link_to new_meeting_feedback_path(@meeting), class:"name_decoration" do %>
          <p class="meeting-hour_name shadowing"><%=@liked_user.name %></p>
        <% end %>
      </div>
    </div>

    <div class="m-2 row-meeting ">
      <div class="col-text font-correction">
      <p  class= "opacity-margin shadowing">aura lieu</p>
      <p class="m-0 meeting-hour shadowing">Le <%= @day %> <%= @month %> à <%= @hour%>h</p>
      <p class= "opacity-margin shadowing">au</p>
      </div>
    </div>
  </div>


    <div class= "card-category-meeting hide-meeting" style = 'background-image: linear-gradient(rgba(74, 222, 222, 0.2) 0%, rgba(6, 73, 93, 0.55) 71.35%, rgba(2, 15, 21, 0.73) 100%), url(<%= "#{@place.photo}" %>);display: block;'>
        <div class="bottom-left-meeting">
          <p><%= @place.category %></p>
          <% if @place.url.match(/^https/) %>
            <a href= "<%= @place.url%>" target ="_blank" style="text-decoration: none;">
            <% else %>
            <a href= "https://www.timeout.fr<%= @place.url%>" target ="_blank" style="text-decoration: none;">
          <% end %>

            <% if @place.name.size >15 %>
            <h2 class="shadowing"><%= @place.name.first(15) %>...</h2>
            <% else %>
            <h2 class="shadowing"><%= @place.name %></h2>
            <% end %>
          </a>
          <!-- <a href="https://www.google.fr/maps/dir//<%= @place.address %>" target ="_blank" class="btn-google"><i class="fas fa-map-marked-alt"></i>  S'y rendre</a> -->
          <% if @place.address.size >34 %>
            <h3 class="shadowing"><%= @place.address.first(34) %>...</h3>
          <% else %>
            <h3 class="shadowing"><%= @place.address %></h3>
          <% end %>
        </div>
    </div>

        <div class="meeting-btn-annulation hide-meeting">
          <%= link_to "Annuler le date",  meeting_lapins_path(@meeting), method: :post, style: "color:white; text-decoration:none;", class: 'shadowing' %>
        </div>
    <div class="loader-logo">
      <p> Comptoir recherche LE bar... </p>
      <svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
      viewBox="0 0 235 189" style="enable-background:new 0 0 235 189;" xml:space="preserve">
        <style type="text/css">
          .st0{fill:none;stroke:url(#left_1_);stroke-width:10;}
          .st1{fill:none;stroke:url(#right_1_);stroke-width:10;}
        </style>
        <linearGradient id="left_1_" gradientUnits="userSpaceOnUse" x1="152.4062" y1="262.813" x2="35.5773" y2="146.6037" gradientTransform="matrix(1 0 0 1 0 -110)">
          <stop offset="0%" stop-color="#4ADEDE">
            <animate attributeName="stop-color" values="#4ADEDE; #2EBCE7; #1CA7EC; #4ADEDE" dur="1.5s" repeatCount="indefinite"></animate>
          </stop>
          <stop offset="100%" stop-color="#000000">
            <animate attributeName="stop-color" values="#1CA7EC; #2EBCE7; #4ADEDE; #1CA7EC" dur="1.5s" repeatCount="indefinite"></animate>
          </stop>
        </linearGradient>
        <path id="left" class="st0" d="M179.3,120.1L141,158.6c-13,13.1-34.2,13.2-47.3,0.1l-85-84.5c-1.4-1.4-1.4-3.6,0-4.9L68.2,9.6
          c1.4-1.4,3.6-1.4,4.9,0l106.2,105.7C180.7,116.6,180.7,118.8,179.3,120.1z"/>
          <linearGradient id="right_1_" gradientUnits="userSpaceOnUse" x1="83.2652" y1="263.2624" x2="198.5264" y2="144.737" gradientTransform="matrix(1 0 0 1 0 -110)">
            <stop offset="0%" stop-color="#4ADEDE">
              <animate attributeName="stop-color" values="#4ADEDE; #2EBCE7; #1CA7EC; #4ADEDE" dur="1.5s" repeatCount="indefinite"></animate>
            </stop>
            <stop offset="100%" stop-color="#4ADEDE">
              <animate attributeName="stop-color" values="#1CA7EC; #2EBCE7; #4ADEDE; #1CA7EC" dur="1.5s" repeatCount="indefinite"></animate>
            </stop>
          </linearGradient>
        <path id="right" class="st1" d="M94.8,158.9l-41.4-40.3L160.6,8.3c1.3-1.4,3.6-1.4,4.9-0.1L225.9,67c1.4,1.3,1.4,3.6,0.1,4.9
           l-83.9,86.3C129.2,171.5,108,171.7,94.8,158.9z"/>
      </svg>
    </div>


<!-- <div class="loader ">
  <ul class="loader opacity-0 ">
    <p id="loader-p"> À la recherche du comptoir idéal</p>
      <li class="margin-loader">
        <div class="circle"></div>
        <div class="ball"></div>
      </li>
      <li>
        <div class="circle"></div>
        <div class="ball"></div>
      </li>
      <li>
        <div class="circle"></div>
        <div class="ball"></div>
      </li>
      <li>
        <div class="circle"></div>
        <div class="ball"></div>
      </li>
      <li>
        <div class="circle"></div>
        <div class="ball"></div>
      </li>
  </ul>
</div> -->