config/routes.rb
Rails.application.routes.draw do
  get 'lapin/show'
  get '/goodbye', to: 'pages#goodbye'
  devise_for :users
  root to: 'pages#home'
  # 'get' to: 'meetings#lapin'
  resources :meetings, only: :show do
    resources :lapins, only: [:create]
    resources :feedbacks

    member do
      get :pre_show
    end
  end
  resources :lapins, only: [:show]

  resources :likes, only: :create
  resources :unlikes, only: :create
  resources :users, only: [:create, :index, :show, :edit, :update, :new]
  resources :availabilities, only: [ :index, :update ]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resource :profile, only: [:show, :update]
end

app/models/user.rb
class User < ApplicationRecord
  DAYS = ["lundi", "mardi",  "mercredi", "jeudi", "vendredi", "samedi", "dimanche"]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  geocoded_by :position
  after_validation :geocode, if: :will_save_change_to_position?
  has_many_attached :photos
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user1_meetings, :class_name => 'Meeting', :foreign_key => 'user1_id'
  has_many :user2_meetings, :class_name => 'Meeting', :foreign_key => 'user2_id'
  has_many :availabilities
  has_many :lapins

  has_many :likes
  has_many :liked_users, through: :likes, class_name: 'User'
  has_many :unlikes
  has_many :unliked_users, through: :unlikes, class_name: 'User'
  # has_many :liked_users, :class_name => 'Like', :foreign_key => 'liked_user_id', dependent: :destroy
  # has_many :unliked_users, :class_name => 'Unlike', :foreign_key => 'unliked_user_id', dependent: :destroy_all


  validates :email, :name, :description, :age, :height, :sex, :sexual_orientation, presence: true
  after_create :create_user_weeks_availabilities
  accepts_nested_attributes_for :availabilities
  has_many :feedbacks

  def afterworks_dispos
    avails = self.availabilities.pluck(:days, :afterwork).delete_if { |arr| arr.last == false }
    avails.map do |arr|
      arr[1] = "afterwork"
      arr
    end
  end

  def diners_dispos
    avails = self.availabilities.pluck(:days, :diner_time).delete_if { |arr| arr.last == false }
    avails.map do |arr|
      arr[1] = "diner_time"
      arr
    end
  end

  def my_dispos
    afterworks_dispos + diners_dispos
  end

  def first_matching_dispo_with(other_user)
    matching_dispos_with(other_user).compact.first
  end

  def matching_dispos_with(other_user)
    my_dispos.map do |dispo|
      dispo if other_user.my_dispos.include?(dispo)
    end
  end

  def interesting_users
    cu_id = self.id
    cu_user = User.find(cu_id)
    list_users = User.all.where.not(id: cu_user.id)
    wanted_users =[]
    case cu_user.sex
    when "Homme"
      if cu_user.sexual_orientation == "hetero"
        list_users.each do |user|
          if user.sex == "Femme" && (user.sexual_orientation == "homo" || user.sexual_orientation == "bi")
            wanted_users << user
          end
        end
      elsif cu_user.sexual_orientation == "homo"
        list_users.each do |user|
          if user.sex == "Homme" && (user.sexual_orientation == "homo" || user.sexual_orientation == "bi")
            wanted_users << user
          end
        end
      elsif cu_user.sexual_orientation == "bi"
        list_users.each do |user|
          if (user.sex == "Femme" && (user.sexual_orientation == "hetero" || user.sexual_orientation == "bi")) || (user.sex =="Homme" && (user.sexual_orientation == "homo" || user.sexual_orientation == "bi"))
            wanted_users << user
          end
        end
      end
    when "Femme"
      if cu_user.sexual_orientation == "hetero"
        list_users.each do |user|
          if user.sex == "Homme" && (user.sexual_orientation == "hetero" || user.sexual_orientation == "bi")
            wanted_users << user
          end
        end
      elsif cu_user.sexual_orientation == "homo"
        list_users.each do |user|
          if user.sex == "Femme" && (user.sexual_orientation == "homo" || user.sexual_orientation == "bi")
            wanted_users << user
          end
        end
      elsif cu_user.sexual_orientation == "bi"
        list_users.each do |user|
        if (user.sex == "Femme" && (user.sexual_orientation == "homo" || user.sexual_orientation == "bi")) || (user.sex == "Homme" && (user.sexual_orientation == "hetero" || user.sexual_orientation == "bi"))
          wanted_users << user
        end
        end
      end
    end
    wanted_users
  end

  def seen_users
    users = interesting_users - self.liked_users
    users - self.unliked_users


    # cu_id = self.id
    # cu_user = User.find(cu_id)
    # list_users = interesting_users
    # wanted_users = []
    # list_users.each do |user|
    #   seen = false
    #   user.liked_users.each do |user|
    #     seen = true if user.id == cu_id
    #   end
    #   user.unliked_users.each do |unlike|
    #     seen = true if unlike.user_id == cu_id
    #   end
    #   wanted_users << user if seen == false
    # end
    # wanted_users
  end

  def create_user_weeks_availabilities
    DAYS.each do |day|
      availability = Availability.new(
        user: self,
        days: day,
        afterwork: true,
        diner_time: true)
      availability.save!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = policy_scope(User)
    @user = current_user
    @like = Like.new
    @unlike = Unlike.new

    unless request.referer.nil?
      if request.referer.include?("lapins")
        message = "#{@user.name}, Comptoir te réouvre ses portes!"
        TwilioTextMessenger.new(message).call(ENV['TWILIO_SID'], ENV['TWILIO_TOKEN'])
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @like = Like.new
    @unlike = Unlike.new
    authorize @user
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to user_path(@user)
    authorize @user
  end

  def edit
    @user.User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    authorize @user
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :description, :job, :intention, :sex, :sexual_orientation, :height, :sport, :smorker?, :drinker?, photos: [], availabilities_attributes: [:id, :afterwork, :diner_time])
  end

  private

  def restaurant_params
    params.require(:user).permit(:email, :password)
  end

end

app/views/users/index.html.erb
<div class="index_wrapper ">
  <div class="cards">
    <% @user.seen_users.each do |user| %>
      <div class="card-profile" id="user-<%= user.id %>">

        <%= link_to user_path(user), class: 'profile-link' do  %>
          <div class="card-presentation d-flex flex-column justify-content-end align-items-start m-auto demo__card" style="background-image:linear-gradient(180deg, rgba(74, 222, 222, 0.05) 71.48%, rgba(46, 188, 231, 0.7) 93.1%, #1CA7EC 100%), url('http://res.cloudinary.com/dlh4cl5ih/image/upload/<%= user.photos[0].key%>')">
            <div>
              <h2 class="card-name"><%= user.name %>, <%= user.age %></h2>
              <% if user.description.size > 70 %>
                <p class="card-description"><%= user.description.first(70) %>...</p>
              <% else %>
                <p class="card-description"><%= user.description %></p>
              <% end %>
            </div>
          </div>
        <% end %>

        <div class="row buttons">
          <div class="col-3">
            <%= simple_form_for @unlike, url: unlikes_path, method: :post do |f| %>
              <%= f.input :unliked_user, input_html: {value: "#{user.id}"}, as: :hidden %>
              <div class="small-3 columns">
                <%= button_tag type: 'submit', class: "button postfix btn btn-next shadowing border-0", id: "next-profile_#{user.id}" do %>
                  <i class="fas fa-times" aria-hidden="true"></i>
                <% end %>
              </div>
              <%#= f.submit 'X', class: "btn btn-next", id: "next-profile_#{user.id}" %>
            <% end %>
          </div>
          <div class="col-9">
            <%= simple_form_for @like, url: likes_path, method: :post do |f| %>
              <%= f.input :liked_user, input_html: {value: "#{user.id}"}, as: :hidden %>
              <%= f.submit "Rencontrer", class: "btn btn-like shadowing border-0", id: "meet-profile_#{user.id}"  do %>
                <!-- <p>
                  <%#= image_tag "LogoComptoir.png", style: "height: 100px;" %>
                  Rencontrer
                </p> -->
              <% end %>
            <% end %>
          </div>
          <div class="d-none">
            <%= link_to user_path(user), class: 'btn-show', id: "show-profile_#{user.id}" %>
          </div>
        </div>
          <%#= link_to likes_path, class: "btn btn-like d-flex justify-content-center" do  %>
          <%# end %>
      </div>
    <% end %>
  </div>
  <div class="calendar" id="calendar-form" >
    <p class="font-correction-availabilities">Mes disponibilités</p>
      <div class="card-centrer font-correction-availabilities" >
  <%= simple_form_for current_user do |m| %>
      <%= m.simple_fields_for :availabilities do |availability| %>
          <div class="d-flex availability-row">
            <div class="card-head col-3 font-correction-availabilities" >
            <%= availability.object.days %>
            </div>
            <div class="input-hour d-flex justify-content-end col-9 font-correction-availabilities">
              <p class="card-text-calendar">
              <%= availability.input :afterwork, input_html: { checked: availability.object.afterwork }, required: false, as: :boolean , label: "18h  <i class='fas fa-briefcase'></i>".html_safe, class: "btn-availabities" , id: "btn-availabity"%>
              <%= availability.input :diner_time, input_html: { checked: availability.object.diner_time },  required: false, as: :boolean, label: "20h  <i class='fas fa-cocktail'></i>".html_safe, class: "btn-availabities" , id: "btn-availabity"%>
              </p>
            </div>
          </div>
          <% end %>
      <%= m.submit 'valider', class: 'btn-validate-availabity' %>
  <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators" style="height: 2vh;margin-bottom: 7%;">
    <%if @user.photos.attached?%>
      <% @user.photos.each_with_index do |photo, index| %>
        <% if index == 0 %>
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <% else %>
          <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>"></li>
        <% end %>
      <% end %>
    <% else %>
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <% end %>
  </ol>


  <div class="carousel-inner rounded-top-corner">
    <%if @user.photos.attached?%>
      <% @user.photos.each_with_index do |photo, index| %>
        <% if index == 0 %>
          <% active_photo = "active" %>
        <% else %>
          <% active_photo = "  " %>
        <% end %>
      <div class="carousel-item <%= active_photo %>">
      <%= cl_image_tag photo.key, class: "justify-content-center w-100", style: "height:65vh;object-fit:cover;"%>
     </div>
     <% end %>
    <% else %>
      <%= image_tag "download.jpeg", alt: "First slide", class: "d-block w-100" %>
    <% end %>
  </div>

  <%if @user.photos.attached?%>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
  <% end %>
</div>

<div class="card-infos">
  <%= link_to users_path do %>
    <i class="fas fa-arrow-circle-up btn-up-index shadowing"></i>
  <% end %>
    <h2 class ="card-nickname shadowing"><%= @user.name %>, <%= @user.age %></h2>
    <p class="card-desc shadowing"><i class="fas fa-ruler"></i> <%= @user.height / 100 %>m <%= @user.height % 100 %></p>
    <p class="card-desc shadowing"><%= @user.description %></p>
  <div class="icone d-flex justify-content-center w-100 icone-center shadowing">
   <!--  <%# if @user.drinker == true %>
      <a class="btn btn-ghost justify-content-center" href="#"> <i class="fas fa-wine-glass-alt"></i> --><!--  <p>  Je bois</p> </a> -->
      <%# else %>
      <!-- <a class="btn btn-ghost justify-content-center" href="#"> --><!-- <i class="fas fa-wine-glass-alt"></i> --> <!-- <p>  Je ne bois pas</p> </a>
    <%#end %> -->
    <%#if @user.smoker == true %>
      <!-- <a class="btn btn-ghost justify-content-center" href="#"> --><!-- <i class="fas fa-smoking"></i> --> <!-- <p>  Je fume</p></a> -->
    <%# else %>
      <!-- a class="btn btn-ghost justify-content-center" href="#"> --><!-- <i class="fas fa-smoking"></i> --><!--  <p>  Je ne fume pas</p></a> -->
    <%# end %>
    <i class="fas fa-dumbbell"></i>
    <i class="fas fa-wine-glass-alt"></i>
    <i class="fas fa-smoking-ban"></i>
    <i class="fas fa-balance-scale"></i>

  </div>
  <div class="card-details">
    <p><%= @user.job %></p>
    <p><%= @user.sport %></p>
  </div>
  <%= link_to "Signaler #{@user.name}", "#", class: "btn btn-signal"%>
</div>

<div class="row buttons-show">
  <div class="col-3">
    <%= simple_form_for @unlike, url: unlikes_path, method: :post do |f| %>
      <%= f.input :unliked_user, input_html: {value: "#{@user.id}"}, as: :hidden %>
      <div class="small-3 columns">
        <%= button_tag type: 'submit', class: "button postfix btn btn-next shadowing border-0", id: "next-profile_#{@user.id}" do %>
          <i class="fas fa-times" aria-hidden="true"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="col-9">
    <%= simple_form_for @like, url: likes_path, method: :post do |f| %>
      <%= f.input :liked_user, input_html: {value: "#{@user.id}"}, as: :hidden %>
      <%= f.submit "Rencontrer", class: "btn btn-like shadowing border-0", id: "meet-profile_#{@user.id}"  do %>
      <% end %>
    <% end %>
  </div>
</div>